Document: blockpad
Title: Debian blockpad Manual
Author: <insert document author here>
Abstract: This manual describes what blockpad is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/blockpad/blockpad.sgml.gz

Format: postscript
Files: /usr/share/doc/blockpad/blockpad.ps.gz

Format: text
Files: /usr/share/doc/blockpad/blockpad.text.gz

Format: HTML
Index: /usr/share/doc/blockpad/html/index.html
Files: /usr/share/doc/blockpad/html/*.html
